window.RecordTypes = {
  normal: 'normal',
  techno: 'techno',
  hiphop: 'hiphop',
  rock: 'rock',
  blues: 'blues',
};

window.Records = {
  t001: {
    name: 'There can be only one',
    artist: 'CJ Bolland',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description: 'A lesson in filtering from CJ Bolland',
  },
  h001: {
    name: "Can't stop won't stop",
    artist: 'KRS One',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: 'Lyrical learnings from the master MC KRSOne',
  },
  r001: {
    name: 'Ramble on',
    artist: 'Led Zepplin',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['groovyStatus', 'damage1'],
    description: 'Lord of the Rings inspired Led Zepplin',
  },
  r002: {
    name: 'War pigs',
    artist: 'Black Sabbath',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['damage1'],
    description: 'Ozzy and the crew will melt your face off',
  },
  b001: {
    name: 'Smokestack lightning',
    artist: "Howlin' Wolf",
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: "Classic Blues from the Howlin' Wolf",
  },
  b002: {
    name: 'On the road again',
    artist: 'Canned Heat',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: 'Awesome blues from Blind Owl and Canned Heat',
  },
  n001: {
    name: "Never goin' back again",
    artist: 'Fleetwood Mac',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: 'Amazing finger picking guitar from Lindsey Buckingham',
  },
  n002: {
    name: 'My old friend the blues',
    artist: 'The Proclaimers',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: 'The Proclaimers. Probably the most underrated band ever',
  },
  n003: {
    name: 'Shaddap you face',
    artist: 'Joe Dolce',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description:
      "Classic one hit wonder from the early 80's and Kev's first vinyl",
  },
  n004: {
    name: "Star Trekkin'",
    artist: 'The Crew',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: "Litigiously similar to 'I am a music man'",
  },
  n005: {
    name: 'Notorious',
    artist: 'Duran Duran',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: 'These really are all records that Kev owns (or owned)',
  },
  n006: {
    name: 'Touch Me',
    artist: 'Samantha Fox',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: "In Kev's defence, this one was bought for him by his sister",
  },
};
