window.RecordTypes = {
  normal: 'normal',
  techno: 'techno',
  hiphop: 'hiphop',
  rock: 'rock',
  blues: 'blues',
};

window.Records = {
  a001: {
    name: 'No more shall we part',
    artist: 'Nick Cave',
    type: RecordTypes.alternative,
    src: '/assets/objects/alternativeRecord.png',
    icon: '/assets/icons/alternative.png',
    actions: ['damage1'],
    description: "Title track from one of Nick Cave's best albums",
  },
  a002: {
    name: 'Trad',
    artist: 'Nadine Shah',
    type: RecordTypes.alternative,
    src: '/assets/objects/alternativeRecord.png',
    icon: '/assets/icons/alternative.png',
    actions: ['damage1'],
    description: "One of Alys' favourite songs by the amazing Nadine Shah",
  },
  a003: {
    name: 'Hyper ballad',
    artist: 'Björk',
    type: RecordTypes.alternative,
    src: '/assets/objects/alternativeRecord.png',
    icon: '/assets/icons/alternative.png',
    actions: ['damage1'],
    description: 'Weird and wonderful alt-house tune from musical genius Björk',
  },
  a004: {
    name: 'Tropicalia',
    artist: 'Beck',
    type: RecordTypes.alternative,
    src: '/assets/objects/alternativeRecord.png',
    icon: '/assets/icons/alternative.png',
    actions: ['damage1'],
    description: 'South American inspired tune from alt pop guru Beck',
  },
  a005: {
    name: 'Drive in Saturday',
    artist: 'David Bowie',
    type: RecordTypes.alternative,
    src: '/assets/objects/alternativeRecord.png',
    icon: '/assets/icons/alternative.png',
    actions: ['damage1'],
    description: 'Virtually any tune from Bowie the king of weird, would do',
  },
  a006: {
    name: 'Professional widow',
    artist: 'Tori Amos',
    type: RecordTypes.alternative,
    src: '/assets/objects/alternativeRecord.png',
    icon: '/assets/icons/alternative.png',
    actions: ['damage1'],
    description: 'Armand Van Heldens remix of this Tori Amos tune is epic!',
  },
  b001: {
    name: 'Smokestack lightning',
    artist: "Howlin' Wolf",
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: "Classic Blues from the Howlin' Wolf",
  },
  b002: {
    name: 'On the road again',
    artist: 'Canned Heat',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: 'Awesome blues from Blind Owl and Canned Heat',
  },
  b003: {
    name: 'O sinnerman',
    artist: 'Nina Simone',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      "Nina Simone's version of the traditional African American song",
  },
  b004: {
    name: 'Today I sing the blues',
    artist: 'Aretha Franklin',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      "This 1969 song from Aretha Franklin is slow blues at it's best",
  },
  b005: {
    name: 'Midnight train to Georgia',
    artist: 'Gladys Knight and the Pips',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      "This Gladys Knight tune is Kev's favourite, at least it is in 2022",
  },
  b006: {
    name: 'Try a little tenderness',
    artist: 'Otis Reading',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      "So many great versions of this song. Kev's fave 2: Otis Reading and The Commitments",
  },
  b006: {
    name: 'Higher and higher',
    artist: 'Jackie Wilson',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      "Awesome uplifting tune from Jackie Wilson",
  },
  c001: {
    name: 'Brandenburg concerto no.3',
    artist: 'Johann Sebastian Bach',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: "Johann Sebastian Bach is Kev's all time classical music hero",
  },
  c002: {
    name: 'Four seasons - autumn',
    artist: 'Antonio Vivaldi',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: "This Vivaldi piece is one of Alys' favourite pieces of music",
  },
  c003: {
    name: 'Moonlight sonata, III - Presto agitato',
    artist: 'Beethoven',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      'Kev would play this frenetic Beethoven piece if he was any good at piano',
  },
  c004: {
    name: 'Piano concerto no.21',
    artist: 'Mozart',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description: 'It turns out that Mozart was quite good at music',
  },
  c005: {
    name: 'The Blue Danube Waltz',
    artist: 'Johan Strauss II',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      'This Strauss Waltz always makes Kev think of space thanks to Stanley Kubrick',
  },
  c006: {
    name: '24th caprice',
    artist: 'Paganini',
    type: RecordTypes.blues,
    src: '/assets/objects/bluesRecord.png',
    icon: '/assets/icons/blues.png',
    actions: ['offKeyStatus', 'damage1'],
    description:
      'This Paganini music was the theme tune for the south bank show',
  },
  h001: {
    name: "Can't stop won't stop",
    artist: 'KRS One',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: 'Lyrical learnings from the master MC KRSOne',
  },
  h002: {
    name: 'Youthful Expression',
    artist: 'Tribe Called Quest',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: 'Early Tribe called quest masterpiece of hip-funk',
  },
  h003: {
    name: 'Work it',
    artist: 'Missy Elliot',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: 'Possibly the coolest tune of all time from Missy Elliot',
  },
  h004: {
    name: 'Paper planes',
    artist: 'M.I.A.',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: 'M.I.A. tune sampling The Clash',
  },
  h005: {
    name: 'Haydn',
    artist: 'Skinny Man',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: "Taken from Skinny Man's Council Estate of Man",
  },
  h006: {
    name: 'Witness',
    artist: 'Roots Manuva',
    type: RecordTypes.hiphop,
    src: '/assets/objects/hiphopRecord.png',
    icon: '/assets/icons/hiphop.png',
    actions: ['groovyStatus', 'offKeyStatus', 'damage1'],
    description: 'Check out the video for this classic Roots Manuva tune',
  },
  n001: {
    name: "Never goin' back again",
    artist: 'Fleetwood Mac',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: 'Amazing finger picking guitar from Lindsey Buckingham',
  },
  n002: {
    name: 'My old friend the blues',
    artist: 'The Proclaimers',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: 'The Proclaimers. Probably the most underrated band ever',
  },
  n003: {
    name: 'Shaddap you face',
    artist: 'Joe Dolce',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description:
      "Classic one hit wonder from the early 80's and Kev's first vinyl",
  },
  n004: {
    name: "Star Trekkin'",
    artist: 'The Crew',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: "Litigiously similar to 'I am a music man'",
  },
  n005: {
    name: 'Notorious',
    artist: 'Duran Duran',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: 'These really are all records that Kev owns (or owned)',
  },
  n006: {
    name: 'Touch Me',
    artist: 'Samantha Fox',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description: "In Kev's defence, this one was bought for him by his sister",
  },
  n007: {
    name: 'Blackbird',
    artist: 'The Beatles',
    type: RecordTypes.normal,
    src: '/assets/objects/normalRecord.png',
    icon: '/assets/characters/blankSquare.png',
    actions: ['damage1'],
    description:
      'If you ask Kev. Sometimes he will say this is his favourite song',
  },
  r001: {
    name: 'Ramble on',
    artist: 'Led Zepplin',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['groovyStatus', 'damage1'],
    description: 'Lord of the Rings inspired Led Zepplin',
  },
  r002: {
    name: 'War pigs',
    artist: 'Black Sabbath',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['damage1'],
    description: 'Ozzy and the crew will melt your face off',
  },
  r003: {
    name: 'No one knows',
    artist: 'Queens of the Stoneage',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['damage1'],
    description: "This QOTSA tune is one of Kev's most covered songs",
  },
  r004: {
    name: 'Everyday is a winding road',
    artist: 'Sheryl Crow',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['damage1'],
    description: "There's a live video of Kev covering this tune on YouTube",
  },
  r005: {
    name: 'Talk of the town',
    artist: 'The Pretenders',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['damage1'],
    description: "The Pretenders are also one of Kev's Mum's favourite bands",
  },
  r006: {
    name: "Rollin' on the River",
    artist: 'Tina Turner',
    type: RecordTypes.rock,
    src: '/assets/objects/rockRecord.png',
    icon: '/assets/icons/rock.png',
    actions: ['damage1'],
    description: 'Kev has covered this Tina Turner tune with multiple bands',
  },
  t001: {
    name: 'There can be only one',
    artist: 'CJ Bolland',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description: 'A lesson in filtering from CJ Bolland',
  },
  t002: {
    name: 'Harder better faster stronger',
    artist: 'Daft Punk',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description:
      "Daft Punk are Kev's production heroes and the inspiration for much of his early music",
  },
  t003: {
    name: 'Everybody loves a carnival',
    artist: 'Fatboy Slim',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description:
      "This Fatboy Slim tune was one of the records that got Kev into dance music in the 90's",
  },
  t004: {
    name: 'Yeah yeah',
    artist: 'Bodyrox',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description:
      'This Bodyrox tune was the signature tune from one of the best summers',
  },
  t005: {
    name: 'I feel love',
    artist: 'Donna Summer',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description: 'Kev has produced a remix of this Donna Summer classic',
  },
  t006: {
    name: 'Windowlicker',
    artist: 'Aphex Twin',
    type: RecordTypes.techno,
    src: '/assets/objects/technoRecord.png',
    icon: '/assets/icons/techno.png',
    actions: ['damage1'],
    description: 'Kev uses this Aphex Twin tune to test out new sound systems',
  },
};
